### PR TITLE
Moved af_ZA translation to top directory

### PR DESCRIPTION
**Pull request by elzette**

### CODE REVIEW

**Comment by sararosso** [comment]
Great that you're ready! Can you please have other members of the Afrikaans community chime in on this thread regarding the translation and if any changes need to be made? That will help us determine if it's ready for official status. Thanks!

**Comment by elzette** [comment]
Thanks Sara - yes, its getting a see-over by Afrikaans experts! Where will this document be available/can be seen online?

**Comment by sararosso** [comment]
@elzette Can you get a few Afrikaans experts to take a look at this translation you submitted, and comment on this thread? If it looks ok to them, I can approve the translation to join the other official ones.

**Comment by elzette** [comment]
@sararosso it's in the process. Did you see my last question from 10 day ago? We would like to know where on the internet this will be accessed? Eg. would it be from https://wordpress.org/about/security/ with link to a Afrikaans version? Is there a list somewhere with all the translations, or is it from the Rosetta site? It would be good to know the context.

**Comment by sararosso** [comment]
@elzette At the moment the GitHub repo is going to be the place to find translations. Most likely each language team will have to decide if they also want to feature it on their Rosetta site.

**Comment by elzette** [comment]
Thank you Sarah!

**Comment by sararosso** [comment]
@elzette Were you able to get a few Afrikaans experts to take a look at this translation? Please have them comment on this thread so we can change or approve the request.

**Comment by sararosso** [comment]
Closing this request due to inactivity. @elzette please submit a new pull request when ready!

**Pull request closed without merging**
