### PR TITLE
es_ES translation done

### PR DESCRIPTION
**Pull request by evelioml**

### CODE REVIEW

**Comment by sararosso** [comment]
@bi0xid Is this the finished translation? Look ok?

**Comment by bi0xid** [comment]
Yes, this is the good one. Both @evelioml and myself have been working on it together. 
Thanks :)

**Comment by sararosso** [comment]
You'll want to submit a pull request to move this to the /es_ES folder when you're ready, so it's out of Working Translations :)

**Comment by bi0xid** [comment]
We'll do :) 
Thanks again.

**Pull request merged**
