### PR TITLE
Change "Kemerdekaan" to "Kebebasan"

### PR DESCRIPTION
**Pull request by afwanwh**
Appropriate translation of "Freedom" word in Indonesian.

### CODE REVIEW

**Comment by sararosso** [comment]
@ekajogja thoughts on this change?

**Comment by ekajogja** [comment]
##### Please refer to [What is free software?](http://www.gnu.org/philosophy/free-sw.en.html)

I'm using the term "kemerdekaan" to emphasize what Richard Stallman was trying to say when he choose the term "free software" (ie. free as in free speech, not free beer).

##### Please refer to Indonesian Constitution: [UUD'45 - Article 28](http://www.setneg.go.id/images/stories/kepmen/legal_product/uud_1945.pdf) about "freedom of speech".

+ English (translation): "The freedom of association and assembly, the freedom of expression of thought, both orally as well as in written form and the like shall be stipulated by law."

+ Indonesian: "”Kemerdekaan berserikat dan berkumpul, mengeluarkan pikiran dengan lisan dan tulisan dan sebagainya ditetapkan dengan undang-undang”

Note: I've contacted the administrator of GNU website to correct the ugly translated [Indonesian version of Free Software definition](http://www.gnu.org/philosophy/free-sw.id.html) since the whole text is dangerously misleading. However, since the translator has long abandoned the project, they still use it on the website - might have to contact Mr. Stallman in person :tongue:

Of course the final decision is in your hand as representative of Automattic. And since this text is an official statement, I believe we can ask opinion from people having background in legal and/or free software activism.

Regards,

**Comment by afwanwh** [comment]
@ekajogja We can't use Indonesian Constitution as reference of "Freedom" translation. Originally, Indonesian Constitution is written in Indonesian language. So, if there are two word "Kemerdekaan" and "Kebebasan" in Indonesian Constitution, both will be translated to "Freedom".

**Comment by ekajogja** [comment]
@afwanwh @sararosso 
I have to refrain from further discussion since I can smell arguments from ignorance.

**Comment by sararosso** [comment]
Thank you both for the discussion. I'm going to close this request - @ekajogja is an official validator for the Indonesian WordPress project so I'll have to trust it's consistent with the rest of his work.

**Pull request closed without merging**
