### PR TITLE
Add Australian English translation.

### PR DESCRIPTION
**Pull request by Japh**
American English and Australian English are very similar, but different
enough to be noticeable in a professional setting.

### CODE REVIEW

**Comment by ntwb** [comment]
:+1:

**Comment by sararosso** [comment]
Great! Go Australian community on getting the translation in working order! When you think the translation is ready to go official, please submit a PR to move it to the top directory, and it would be great if a few others from your community could sign off on the PR as well before I approve it! :)

**Comment by Japh** [comment]
Thanks, @sararosso!

@bronsonquick @dd32 @pento @rmccue @om4james Can I get some more eyes and :+1:s on this please? :smile:

**Comment by ntwb** [comment]
:+1: Yeah this ridgy didge translation pass's the fair dinkum Aussie translation requirements :)

And whilst we're at it on pinging Aussies, my canonical reference of the Australian translations currently lives here, pull requests welcome: https://translate.wordpress.org/projects/wp/dev/en-au/default/glossary

**Comment by dd32** [comment]
:+1: 
Since there's no history on the new file, it's nearly impossible to see the alterations made, upon review by diff'ing the two files locally shows the changes are good, although i haven't checked for any missed words.

**Pull request merged**
